lookup_subnet: 10.182.20.217/24

systems:
- name: micro1
  ovn_uplink_interface: enp6s0
  storage:
    local:
      path: /dev/sdb
      wipe: true
    ceph:
    - path: /dev/sdc
      wipe: true
- name: micro2
  ovn_uplink_interface: enp6s0
  storage:
    local:
      path: /dev/sdb
      wipe: true
    ceph:
    - path: /dev/sdc
      wipe: true
- name: micro3
  ovn_uplink_interface: enp6s0
  storage:
    local:
      path: /dev/sdb
      wipe: true
    ceph:
    - path: /dev/sdc
      wipe: true

ovn:
  ipv4_gateway: 10.179.193.1/24
  ipv4_range: 10.179.193.10-10.179.193.254
  ipv6_gateway: fd42:4b61:2f69:c09f::1/64
